apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type stdout
    </match>
