apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: {{ .Values.flaskApp.replicas }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: {{ .Values.flaskApp.image }}
          ports:
            - containerPort: {{ .Values.flaskApp.port }}
          env:
            - name: DB_URL
              value: postgresql://{{ .Values.flaskApp.env.POSTGRES_USER }}:{{ .Values.flaskApp.env.POSTGRES_PASSWORD }}@{{ .Values.flaskApp.env.POSTGRES_HOST }}:5432/{{ .Values.flaskApp.env.POSTGRES_DB }}
        # Fluent sidecar container to collect logs
        - name: fluentd-sidecar
          image: fluent/fluentd:latest
          ports:
            - containerPort: 24224
              name: fluentd
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
      restartPolicy: Always
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-configmap
