# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgres-db-lb
  selector:
    matchLabels:
      app: postgresql-db
  replicas: {{ .Values.postgresql.replicas }}
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: {{ .Values.postgresql.image }}
        volumeMounts:
        - name: postgresql-db-disk
          mountPath: /data
        # Config from ConfigMap
        envFrom:
        - configMapRef:
            name: postgres-db-config
  # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.postgresql.volumeClaimTemplates.storage }}
