version: "3.9"

services:
  flask_msg_app:
    container_name: flask_msg_app
    image: flask_msg_app:0.2.5
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_msg_db:5432/postgres
    depends_on:
      - flask_msg_db
  flask_msg_db:
    container_name: flask_msg_db
    image: postgres:14.1-alpine
    #restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: