---
# apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-dev-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.CertManager.letsEncryptClusterIssuer.emailAddress }}"
    privateKeySecretRef:
      name: letsencrypt-issuer-dev-dns01
    solvers:
    - selector: {}
      dns01:
        route53:
          region: "{{ .Values.CertManager.letsEncryptClusterIssuer.route53.region }}"
          role: arn:aws:iam::315375854055:role/cert-manager
