apiVersion: v2
icon: https://bitnami.com/assets/stacks/external-dns/img/external-dns-stack-110x117.png
name: external-dns
description: A Helm chart for installing external-dns.

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
    - name: external-dns
      version: 6.7.0
      repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
      alias: external-dns