cloudProvider: aws
awsRegion: ap-south-1
nameOverride: aws-cluster-autoscaler
rbac:
  create: true
  serviceAccount: 
    create: true
    name: cluster-autoscaler
    annotations: {
      eks.amazonaws.com/role-arn: arn:aws:iam::315375854055:role/cluster-autoscaler
    }

image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.22.3
