postgresql:
  env:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres   # Its not safe here. This credential is be passed through CI/CD tool.
    PGDATA: /data/pgdata
